# Generated by Django 4.2.7 on 2023-11-14 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('returnFrequentRenter', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmationId', models.CharField(max_length=20)),
                ('bookingSource', models.CharField(max_length=20)),
                ('givenName', models.CharField(max_length=50)),
                ('middleName', models.CharField(blank=True, max_length=50, null=True)),
                ('surname', models.CharField(max_length=50)),
                ('returnOnly', models.JSONField(default=list)),
                ('unmaskPaymentCardNumbers', models.BooleanField(default=False)),
                ('extraFeatures', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='booking.extrafeatures')),
            ],
        ),
    ]
